### ISSUE TITLE
Reconsider the inclusion of .sca, .vca, .fra, etc files

### ISSUE THREAD

**Issue by StevenBlack** [cwollenhaupt/foxGitIgnore#1]
I recommend these lines should not be in `.gitignore` because it nullifies a key feature of git and GitHub: the ability to diff two arbitrary versions from history, or diff the current working version from the most recent version in your index.

These plaintext artefacts are extremely valuable.

https://github.com/cwollenhaupt/foxGitIgnore/blob/b76f43ce49cebc679429469a192a4651f34a3288/.gitignore.example#L35-L42

**Comment by StevenBlack** [comment]
* I'm happy to submit a PR for this.

**Comment by StevenBlack** [comment]
The same applies to these lines:

https://github.com/cwollenhaupt/foxGitIgnore/blob/b76f43ce49cebc679429469a192a4651f34a3288/.gitignore.example#L1-L13

**Comment by cwollenhaupt** [comment]
This is kind of the same issue as in #2: Which files belong into the repository? Storing SCX/SCT/SCA in the repository is the way that VSS works. It admittedly is what FoxPro developers have grown up with, so it kind of feels like the natural way. The same is trues for putting release artifacts into the repository which is still common with FoxPro repositories, but has been replaced by package managers pretty much everywhere else.

As a single developer who uses git to keep a history of their work you probably won't notice much differences between git and VSS. Generate the *.*a files, commit changes and push to a remote to store a backup. But then you are also not benefiting from the many advantages of git which lets you make changes isolated from other changes and only pull into the main branch what has been tested, approved and is working. 

As a team this approach fails to work. VSS, CVS and SVN provide a single linear history that cannot be rewritten. git, on the other hand, uses a network of commits. The crucial part is being able to merge quickly and automatically. Any manual intervention is a cause for errors. Rebuilding a project will change all binary files if you use include files, because the time stamp of the include file is stored in the binary file. With git these include files will always have different time stamps between different developers. 

You can either agree on checking in only files that are actually modified which means you need to manually wade through all modified files, or you commit files that are changed which results in a terrible experience when you need to merge changes, because then you get a merge conflict on every single file.

SCX, etc. are one way files. You cannot recreate the binary from the SCA file. That requires you to store the binaries (to work on) and the textual representations (for comparison). When you merge changes, you need to resolve two sets of files with the same changes and have to make sure that you resolve them the same way in both cases. 

We tried to work on setups like this in git as a team (or in SVN, actually, were it causes the same issues), and I really, really do not want to go back there. The approach is fine for a single developer, but not for a team.

**Comment by StevenBlack** [comment]
I think the central point here is the `readme` should specify this `.gitignore` works only under very specific development conditions particular to your personal tooling and workflows. I think the readme in this repo should feature a prominent warning related to that.

I can't recommend this `.gitignore` for general use because of all its hidden, unstated, tooling-specific  presumptions.

Regardless, not wanting `.sca`, `.vca`, etc files in git is a real head scratcher.  🙄  Whatever, Christof.  Makes zero sense to me.

**Comment by cwollenhaupt** [comment]
I agree that the first readme did not made clear when this .gitignore file isn't suitable. I added a paragraph, because with single developers using linear history, there is indeed a very specific development condition when using this .gitignore file does not make sense. It's admittedly not a situation I've faced for a long time.

The supported tooling is the standard FoxPro tooling for distributed versioning systems that has been covered for many, many years at conferences and back then even in the few magazines the community had.

The beauty of open source is that you have many choices. This is just another choice that is available to developers. I appreciate the discussion, though. I'm sure your thoughts will help others to decide whether this particular file is useful to them or not.
